<?php

/**
 * @file
 * Contains bowling_field.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function bowling_field_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bowling_field module.
    case 'help.page.bowling_field':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A field to record bowling scores.') . '</p>';
      return $output;

    default:
  }
}
